services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: portfoliopulse-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-portfoliopulse_root_2024}
      MYSQL_DATABASE: ${DB_NAME:-portfolio_pulse}
      MYSQL_USER: ${DB_USER:-portfoliopulse}
      MYSQL_PASSWORD: ${DB_PASSWORD:-portfoliopulse_2024}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - portfoliopulse-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: portfoliopulse-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://${DB_USER:-portfoliopulse}:${DB_PASSWORD:-portfoliopulse_2024}@mysql:3306/${DB_NAME:-portfolio_pulse}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      RUST_LOG: ${LOG_LEVEL:-info}
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - portfoliopulse-network
    volumes:
      - ./logs:/app/logs

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: portfoliopulse-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - portfoliopulse-network

  # Nginx 反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: portfoliopulse-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - portfoliopulse-network

volumes:
  mysql_data:
    driver: local

networks:
  portfoliopulse-network:
    driver: bridge
